### ISSUE TITLE
Besoin d'aide

### ISSUE THREAD

**Issue by Asahin19** [Manpapper/BattleBrothers_Traduction_FR#1]
Bonjour,

Désolé de passer par ce biai mais souhaiterais-tu de l'aide pour les traductions ?

Cordialement

**Comment by Manpapper** [comment]
Salut,

Oui, n'hésite pas à récupérer le git et à mettre à jour les fichiers.
Je suis sur les évènements https://github.com/Manpapper/BattleBrothers_Traduction_FR/tree/main/scripts/events/events
Je les traite dans l'ordre alphabétique donc tu peux commencer par la fin (sauf le dernier qui est déjà traduit).

J'espère que tu t'y connais en programmation et en utilisation du git car tous les textes sont dans le code.

Merci à toi.

**Comment by Manpapper** [comment]
N'hésite pas à m'ajouter sur discord Manpapper#4182
